#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local url_portainer_Darwin="https://github.com/portainer/portainer/releases/download/${PORTAINER_VERSION}/portainer-${PORTAINER_VERSION}-darwin-amd64.tar.gz"
  local url_portainer_Linux="https://github.com/portainer/portainer/releases/download/${PORTAINER_VERSION}/portainer-${PORTAINER_VERSION}-linux-amd64.tar.gz"

  local url_portainer="url_portainer_$(uname -s)"
  local fnm_portainer="$(basename "${!url_portainer}")"
  cache curl "$fnm_portainer" "${!url_portainer}"
  
  mkdir -p "$shome/vendor"
  pushd "$shome/vendor"
  tar xfz "/data/cache/curl/$fnm_portainer"
  popd
}

bootstrap
