#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_portainer="$(portainer --version 2>&1 || true)"
  jq -n --arg portainer "$ver_portainer" '{portainer: $portainer}'
}

version "$@"
